# Generated by Django 6.0.1 on 2026-01-27 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('error', 'error')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type'], name='events_even_event_t_116895_idx'), models.Index(fields=['created_at'], name='events_even_created_c39501_idx')],
            },
        ),
    ]
